// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kbWTfF6Jwt8_cKdPMy9CCwJEVMrVlLM',
    appId: '1:901612437131:web:07890e6014dae6ca71de8e',
    messagingSenderId: '901612437131',
    projectId: 'projeto-gasto-ntt',
    authDomain: 'projeto-gasto-ntt.firebaseapp.com',
    storageBucket: 'projeto-gasto-ntt.appspot.com',
    measurementId: 'G-YMRDBW2QWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGhuhQipsOi4U4cPJSG6La7HU6pTjVekI',
    appId: '1:901612437131:android:c2b583455c40ef0471de8e',
    messagingSenderId: '901612437131',
    projectId: 'projeto-gasto-ntt',
    storageBucket: 'projeto-gasto-ntt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd8vlYeNvH2e3vWQS1W3LKcK14MRYuO0',
    appId: '1:901612437131:ios:5a2cf8d031117f5671de8e',
    messagingSenderId: '901612437131',
    projectId: 'projeto-gasto-ntt',
    storageBucket: 'projeto-gasto-ntt.appspot.com',
    iosClientId: '901612437131-l1t9u8lvv3ga4shcq16o5poe8q9pa78m.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoGastoNtt',
  );
}
